# Problem 1

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a=np.random.randint(0,10,size=(5))
print(a)
# 3 - matris'in boyutunu öğrenin
print(a.shape)
print(a.ndim)
# 4 - matris'i yeniden boyutlandırın
x=a.reshape(5,1)
# 5 - matris'in boyut sayısını öğrenin
print(x.ndim)


[7 4 1 6 0]
(5,)
1
2


# Problem 2

In [40]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
import numpy as np

a = np.arange(1, 11, 2).reshape(1,5)

print(a)
# 2 - Oluşturduğunuz matrisi parçalayın
print(np.split(a,[1,2]))

# 3 - Parçalanmış matrisleri birleştirin

#print(np.concatenate([a,a]))

[[1 3 5 7 9]]
[array([[1, 3, 5, 7, 9]]), array([], shape=(0, 5), dtype=int32), array([], shape=(0, 5), dtype=int32)]


In [47]:
import numpy as np

matris = np.array([[1, 3, 5], [7, 9, 1], [5, 7, 9]])
print(matris)



[[1 3 5]
 [7 9 1]
 [5 7 9]]


In [48]:
x= np.split(matris, 2)
print(x)


ValueError: array split does not result in an equal division

# Problem 3

In [43]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
import numpy as np

arr = np.arange(5, 101, 2)
np.random.shuffle(arr)

matrix = arr[:20].reshape(10, 2)

print(matrix)
# 2 - matris'in özelliklerini inceleyin
print(matrix.ndim)
print(matrix.shape)
print(matrix.size)
print(matrix.dtype)


[[51 97]
 [15 65]
 [21 75]
 [29 63]
 [95 59]
 [69 25]
 [31 77]
 [17 53]
 [85 33]
 [43 11]]
2
(10, 2)
20
int32
