# Numpy
- sayısal işlemleri hızlı yapmak için C dili ile yazılmış bir python kütüphanesidir.
- veri analizinde kullanılır
- bilgisayar kurmak için pip install numpy komutu ile kurulabilir.
- bilimsel hesaplamalar için kullanılır
- arraylar / çok boyutlu arraylar ve matrisler üzerinde yüksek performanslı işlemler yapılabilir.
- temelleri 1995 yılında atıldı. Ama nihai olarak 2005 yılında Travis Oliphant tarafından hayata geçirilmiştir.
- listelere benzerdir. fakat verimli veri saklma ve vektör işlemleri için Numpy kullanılır. 


In [ ]:
pip install numpy

### Neden Numpy?

In [1]:
# klasik yöntem
a=[1,2,3,4]
b=[2,3,4,5]
ab=[]
for i in range(0,len(a)):
    ab.append(a[i]*b[i])
print(ab)

[2, 6, 12, 20]


In [2]:
# numpy ile
import numpy as np
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
print(a*b)

[ 2  6 12 20]


##### .reshape() fonksiyonu ile arraylarin boyutlarını değiştirebiliriz.

In [3]:
x=np.array([1,2,3,4,5,6,7,8,9])
multi=x.reshape(3,3)
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##### .shape ile arraylarin boyutlarını öğrenebiliriz.

In [4]:
print(multi.shape)

(3, 3)


In [5]:
print(x.shape)

(9,)


##### .ndim ile arraylarin boyut sayısını öğrenebiliriz.

In [6]:
print(x.ndim)

1


In [7]:
print(multi.ndim)

2


### Birleştirme (Concatenation)
- concatenate() fonksiyonu ile birleştirme yapabiliriz

In [8]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10])
print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
z=np.array([11,12,13,14,15])
print(np.concatenate([x,y,z]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [10]:
a=np.array([[1,2,3,],[4,5,6]])
print(np.concatenate([a,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


##### axis=0 satır bazında birleştirme yapar
##### axis=1 sütun bazında birleştirme yapar

In [11]:
print(np.concatenate([a,a],axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


### Array Ayırma (Splitting)
- .split() fonksiyonu ile array ayırma yapabiliriz

In [12]:
m=np.array([1,2,3,99,99,3,2,1])
print(np.split(m,[3,5]))

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]


In [14]:
a,b,c=np.split(m,[3,5])
print(a)
print(b)
print(c)

[1 2 3]
[99 99]
[3 2 1]


- .vsplit() fonksiyonu ile array yatay olarak ayırma yapabiliriz.

In [15]:
n=np.arange(16).reshape(4,4)
np.vsplit(n,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

- .hsplit() fonksiyonu ile array dikey olarak ayırma yapabiliriz.

In [16]:
np.hsplit(n,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

- np.arange(): belli bir aralıkta sayıları oluşturmak için kullanılır. np.arange(start,stop,step)

In [17]:
np.arange(3,12,2)

array([ 3,  5,  7,  9, 11])

- np.zeros(): 0'lardan oluşan bir numpy dizisi oluşturması için kullanılır.

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

- np.ones(): 1'lerden oluşan bir numpy dizisi oluşturulması için kullanılır.

In [19]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

- np.linspace(): belli bir aralıkta sayıları oluşturmak için kullanılır. np.linspace(başlangıç,bitiş,bölünecek aralık)

In [21]:
np.linspace(0,100,5) # beş aralığa böldü

array([  0.,  25.,  50.,  75., 100.])

In [25]:
np.random.randint(0,10,3) # sıfırla on arasında rastgele üç sayı üretti

array([5, 3, 2])

In [26]:
np.random.randint(2,22,5)

array([10,  3, 14,  7,  3])

In [27]:
npArray=np.arange(50)
npMulti=npArray.reshape(5,10)
print(npMulti.sum(axis=1))

[ 45 145 245 345 445]


### Numpy Array'in Özellikleri
- ndim: boyut sayısı
- shape: boyut bilgisi
- size: toplam eleman sayısı
- dtype: veri tipi

In [29]:
a=np.random.randint(10,size=10)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(10,)
10
int32


#### Array Sıralama(Sorting)
- array sıralama işlemleri yapmak için numpy kütüphanesinde yer alan sort() fonksiyonu kullanılır.

In [30]:
v=np.array([8,24,232,12,5,42,55])
print(v)
v.sort()
print(v)

[  8  24 232  12   5  42  55]
[  5   8  12  24  42  55 232]


In [31]:
m=np.random.normal(20,5,(3,3)) # 20-5 arasında 3e 3lük
print(m)

[[ 3.86476174 16.58084229 20.86169826]
 [11.59954268 11.29346584 22.87220859]
 [20.00739264 14.90563113 13.00083187]]


In [32]:
print(np.sort(m,axis=0))

[[ 3.86476174 11.29346584 13.00083187]
 [11.59954268 14.90563113 20.86169826]
 [20.00739264 16.58084229 22.87220859]]


In [33]:
print(np.sort(m,axis=1))

[[ 3.86476174 16.58084229 20.86169826]
 [11.29346584 11.59954268 22.87220859]
 [13.00083187 14.90563113 20.00739264]]


### Index ile Elemanlara Erişmek
- aynı listelerde olduğu gibi index ile elemanlara erişebiliriz.

In [34]:
a=np.random.randint(10,size=10)
print(a[0])

9


In [35]:
print(a[-1])

1


In [36]:
a[0]=100
print(a)

[100   6   9   2   0   3   6   8   2   1]


In [37]:
x=np.random.randint(10,size=(3,5))
print(x)

[[6 4 6 1 5]
 [7 6 9 6 7]
 [8 4 9 5 5]]


In [38]:
print(x[0,0])

6


In [39]:
print(x[1,1])

6


In [40]:
x[1,4]=100
print(x)

[[  6   4   6   1   5]
 [  7   6   9   6 100]
 [  8   4   9   5   5]]


In [41]:
x[1,4]=3.14
print(x)

[[6 4 6 1 5]
 [7 6 9 6 3]
 [8 4 9 5 5]]


### Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [42]:
a=np.arange(20,30)
print(a)

[20 21 22 23 24 25 26 27 28 29]


In [43]:
print(a[0:3])

[20 21 22]


In [44]:
print(a[:3])

[20 21 22]


In [45]:
print(a[3:])

[23 24 25 26 27 28 29]


In [46]:
print(a[1::2])

[21 23 25 27 29]


In [47]:
print(a[0::2])

[20 22 24 26 28]


In [48]:
print(a[2::2])

[22 24 26 28]


In [49]:
print(a[1::5])

[21 26]


In [50]:
b=np.random.randint(10,size=[5,5])
print(b)

[[4 9 8 4 2]
 [3 1 4 1 4]
 [8 4 9 3 1]
 [7 3 2 9 0]
 [1 6 7 0 5]]


In [52]:
print(b[:,0])

[4 3 8 7 1]


In [53]:
print(b[:,1])

[9 1 4 3 6]


In [54]:
print(b[0,:])

[4 9 8 4 2]


In [55]:
print(b[1,:])

[3 1 4 1 4]


In [57]:
print(b[0:2,0:3])

[[4 9 8]
 [3 1 4]]


In [58]:
print(b[::2,::2])

[[4 8 2]
 [8 9 1]
 [1 7 5]]


### Alt Küme Üzerinde İşlem Yapmak

In [60]:
alt_b=b[0:3,0:2]
alt_b

array([[4, 9],
       [3, 1],
       [8, 4]])

In [61]:
alt_b[0,0]=100
alt_b[1,1]=200
alt_b

array([[100,   9],
       [  3, 200],
       [  8,   4]])

In [62]:
print(b)

[[100   9   8   4   2]
 [  3 200   4   1   4]
 [  8   4   9   3   1]
 [  7   3   2   9   0]
 [  1   6   7   0   5]]


### Fancy Index
- bir liste içine bu arrayden istediğimiz indislerini koyarak o indislerdeki verileri alabiliriz.

In [63]:
v=np.arange(0,30,3)
print(v)

[ 0  3  6  9 12 15 18 21 24 27]


In [65]:
yetgen=[1,3,5]
print(v[yetgen])

[ 3  9 15]


In [67]:
m=np.arange(9).reshape(3,3)
satir=np.array([0,1])
sutun=np.array([1,2])
print(m[satir,sutun])

[1 5]


### Koşullu Eleman İşlemleri

In [68]:
v=np.array([1,2,3,4,5])
print(v>3)

[False False False  True  True]


In [69]:
print(v[v>3])

[4 5]


In [70]:
print(v[v<3])

[1 2]


In [71]:
print(v[v>=3])

[3 4 5]


In [72]:
print(v[v<=3])

[1 2 3]


In [73]:
print(v[v!=3])

[1 2 4 5]


In [74]:
print(v[v==3])

[3]


### Matematiksel İşlemler

In [75]:
v=np.array([1,2,3,4,5])
print(v*2)

[ 2  4  6  8 10]


In [76]:
print(v+2)

[3 4 5 6 7]


In [77]:
print(v*5/10)

[0.5 1.  1.5 2.  2.5]


In [78]:
print(v**2)

[ 1  4  9 16 25]


In [79]:
print(np.subtract(v,3)) # Her birinden 3 çıkarıyor

[-2 -1  0  1  2]


In [80]:
print(np.add(v,2)) # toplama

[3 4 5 6 7]


In [81]:
np.multiply(v,2) # çarpma

array([ 2,  4,  6,  8, 10])

In [82]:
np.divide(v,2) # bölüm

array([0.5, 1. , 1.5, 2. , 2.5])

In [83]:
np.power(v,2) # üs alma

array([ 1,  4,  9, 16, 25], dtype=int32)

In [84]:
np.mod(v,5) # mod alma

array([1, 2, 3, 4, 0], dtype=int32)

In [85]:
print(np.absolute(v)) # mutlak değer alma

[1 2 3 4 5]


In [86]:
print(np.sin(360))

0.9589157234143065


In [87]:
np.log(10)

2.302585092994046

In [88]:
?np

Type:        module
String form: <module 'numpy' from 'c:\\Users\\BEYZANUR\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\beyzanur\appdata\local\programs\python\python311\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code sn

#### İki Bilinmeyenli Denklem Çözümü

In [90]:
# 5*x0 + x1=12
# x0 + 3*x1=10
a=np.array([[5,1],[1,3]])
b=np.array([12,10])
x=np.linalg.solve(a,b)
print(x)

[1.85714286 2.71428571]
