# Problem 1 

In [3]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
a=np.array([12,76,33,100,98])
print(a)
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
a.sort()
print(a)

[ 12  76  33 100  98]
[ 12  33  76  98 100]


# Problem 2

In [17]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
x=np.array([10,15,30,45,60])
print("x sonucu",x)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
y=np.random.normal(15,5,(3,3))
print("y sonucu",y)
 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
c=np.arange(50,100,5)
print("c sonucu",c)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
a=np.zeros(10)
print("a sonucu",a)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
b=np.ones(10)
print("b sonucu",b)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.


# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
d=np.random.randint(10,30,5)
print("d sonucu",d)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
s=np.random.randint(-1,2,10)
print("s sonucu",s)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
z=np.random.normal(50,10,(3,5))
print("z sonucu",z)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?


# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?


# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?


# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.


# 14- Üretilen dizinin elemanlarını tersten yazdırın.


# 15- Üretilen matrisin ilk satırını seçiniz.


# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?


# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.


# 18- Üretilen matrisin her bir elemanının karesini alınız.


# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.


x sonucu [10 15 30 45 60]
y sonucu [[ 4.75796273 13.39650302 18.06091077]
 [18.06275044  8.77435372 10.80815153]
 [ 6.68572144 11.64282283 12.23379784]]
c sonucu [50 55 60 65 70 75 80 85 90 95]
a sonucu [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
b sonucu [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
d sonucu [17 13 14 11 21]
s sonucu [ 1  0  1 -1 -1 -1 -1  1  1  0]
z sonucu [[60.79772498 47.07112651 54.0797033  31.2902636  43.35130839]
 [46.91895367 44.13929507 44.14811546 40.0867086  58.22375865]
 [45.62524106 29.63485067 43.17212587 51.48794839 38.01995978]]
