# Problem 1 

In [3]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
a=np.array([12,76,33,100,98])
print(a)
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
a.sort()
print(a)

[ 12  76  33 100  98]
[ 12  33  76  98 100]


# Problem 2

In [20]:
import numpy as np
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
a=np.array([10,15,30,45,60])
print("1-",a)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
b=np.arange(5,16)
print("2-",b)
 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
c=np.arange(50,100,5)
print("3-",c)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
d=np.zeros(10)
print("4-",d)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
e=np.ones(10)
print("5-",e)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
f=np.linspace(0,100,5)
print("6-",f)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
g=np.random.randint(10,31,5)
print("7-",g)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
h=np.random.uniform(-1,1,10)
print("8-",h)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
i=np.random.randint(10,51,size=(3,5))
print("9-",i)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satirToplam=i.sum(axis=1)
print("satır toplamı:",satirToplam)
sutunToplam=i.sum(axis=0)
print("sütun toplamı:",sutunToplam)
toplam=satirToplam.sum()+sutunToplam.sum()
print("toplam:",toplam)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
buyuk=np.amax(i)
print("en büyük sayı:",buyuk)
kucuk=np.amin(i)
print("en küçük sayı:",kucuk)
ort=np.mean(i)
print("ortalama:",ort)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
index=np.argmax(i)
print("12-",index)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
j=np.arange(10,21)
print("13-",j[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print("14-",j[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
k=np.random.randint(10,51,size=(3,5))
print(k)
print("15-",k[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print("16-",k[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print("17-",k[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print("18-",k*2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
m=np.random.randint(-50,50,size=(5,5))
print("19-",m[(m>0)&(m%2==0)])



1- [10 15 30 45 60]
2- [ 5  6  7  8  9 10 11 12 13 14 15]
3- [50 55 60 65 70 75 80 85 90 95]
4- [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
5- [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
6- [  0.  25.  50.  75. 100.]
7- [14 11 20 27 14]
8- [ 0.46215033  0.62602053  0.62379038  0.66769263 -0.61100519  0.39212882
  0.17636354 -0.34404693  0.43010687  0.03972188]
9- [[24 36 29 39 16]
 [44 44 50 25 48]
 [13 49 12 11 21]]
satır toplamı: [144 211 106]
sütun toplamı: [ 81 129  91  75  85]
toplam: 922
en büyük sayı: 50
en küçük sayı: 11
ortalama: 30.733333333333334
12- 7
13- [10 11 12]
14- [20 19 18 17 16 15 14 13 12 11 10]
[[19 34 20 34 29]
 [42 47 18 24 46]
 [31 13 17 12 11]]
15- [19 34 20 34 29]
16- 18
17- [19 42 31]
18- [[38 68 40 68 58]
 [84 94 36 48 92]
 [62 26 34 24 22]]
19- [34 28 40  2 20]
